from blatann.gatt import gatts
from blatann.uuid import Uuid128

PERIPHERAL_NAME = "DB-X02"

# Configuration Service
CONFIGURATION_SERVICE_UUID = Uuid128("CE1310B0-F074-3EA1-EE45-3038D48CAD8A")
CONFIGURATION_SERVICE_SETTINGS_CHARACTERISTIC_UUID = CONFIGURATION_SERVICE_UUID.new_uuid_from_base(0x46AA)
CONFIGURATION_SERVICE_RESPONSE_CHARACTERISTIC_UUID = CONFIGURATION_SERVICE_UUID.new_uuid_from_base(0x46AB)
CONFIGURATION_SERVICE_CRC_CHARACTERISTIC_UUID = CONFIGURATION_SERVICE_UUID.new_uuid_from_base(0x46AC)

# Pressure Service
PRESSURE_SERVICE_UUID = Uuid128("CE1310B0-F074-3EA1-EE45-3038D78CAD8A")
PRESSURE_SERVICE_PRESSURE_CHARACTERISTIC_UUID = PRESSURE_SERVICE_UUID.new_uuid_from_base(0x46B0)

# Temperature Service
TEMPERATURE_SERVICE_UUID = Uuid128("CE1310B0-F074-3EA1-EE45-3038D58CAD8A")
TEMPERATURE_SERVICE_TEMPERATURE_CHARACTERISTIC_UUID = TEMPERATURE_SERVICE_UUID.new_uuid_from_base(0x46AD)
TEMPERATURE_SERVICE_INSTANT_TEMPERATURE_CHARACTERISTIC_UUID = TEMPERATURE_SERVICE_UUID.new_uuid_from_base(0x46AF)

# ECG Service
ECG_SERVICE_UUID = Uuid128("CE1310B0-F074-3EA1-EE45-3038D68CAD8A")
ECG_SERVICE_ECG_CHARACTERISTIC_UUID = ECG_SERVICE_UUID.new_uuid_from_base(0x46AE)
ECG_SERVICE_INSTANT_ECG_CHARACTERISTIC_UUID = ECG_SERVICE_UUID.new_uuid_from_base(0x46B1)